# filepath: deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-openai-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-openai-test-app
  template:
    metadata:
      labels:
        app: azure-openai-test-app
    spec:
      containers:
      - name: azure-openai-test-app
        image: mtsimmons/azure-openai-test-app:latest
        ports:
        - containerPort: 3000