# filepath: service.yaml
apiVersion: v1
kind: Service
metadata:
  name: azure-openai-test-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: azure-openai-test-app